In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
li1 = [
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [4, 5, 6]
]

print(li1)
print(type(li1))

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
<class 'list'>


In [7]:
arr3 = np.array([
    [[1, 2],
     [3, 4]],
    [[5, 6],
     [7, 8]]
])

print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [9]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
range_arr = np.arange(1, 10, 2)
print(range_arr)

[1 3 5 7 9]


In [11]:
# 데이터 타입

정수 = np.array([1, 2, 3, 4, 5])
정수.dtype

dtype('int64')

In [12]:
실수 = np.array([1.5, 2.5, 3.5])
실수.dtype

dtype('float64')

In [13]:
# 배열 속성

arr1 = np.array([1, 2, 3, 4])
arr1.shape

(4,)

In [15]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr2.shape

(2, 3)

In [16]:
arr3 = np.array([
    [[1, 2],
     [3, 4]],
    [[5, 6],
     [7, 8]]
])

arr3.shape

(2, 2, 2)

In [18]:
# ndim
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [19]:
# size - 배열의 총 요소 수를 알려준다

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.size)

5


In [20]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2.size)

6


In [22]:
arr3 = np.array([
    [[1, 2],
     [3, 4]],
    [[5, 6],
     [7, 8]]
])

print(arr3.size)

8
